adding more script

diff --git a/azure-boostrap.yaml b/azure-boostrap.yaml
--- a/azure-boostrap.yaml
+++ b/azure-boostrap.yaml
@@ -64,7 +64,59 @@ jobs:
       echo "Pool ID: $poolId"
 
       # Define the URL to get all agents in the pool
-      url="https://dev.azure.com/${organization}/_
+      url="https://dev.azure.com/${organization}/_apis/distributedtask/pools/${poolId}/agents?includeCapabilities=true&api-version=7.1"
+
+      response=$(curl -s -w "%{http_code}" "${headers[@]}" -X GET "$url")
+      http_code=${response: -3}
+      content=${response::-3}
+
+      if [ $http_code -eq 200 ]; then
+          # Extract all userCapabilities names for online and enabled agents as a unique list
+          capabilityNames=$(echo "$content" | jq -r '[.value[] | select(.status == "online" and .enabled == true) | .userCapabilities | keys] | unique | flatten | join("\n- ")')
+      else
+          echo "Failed to retrieve agent capabilities. HTTP Status Code: $http_code"
+          echo "Response: \"$content\""
+          exit 1
+      fi
+      echo "Unique userCapabilities names: \"$capabilityNames\""
+
+      # Prepare the parameters
+      parametersJson=$(jq -n --arg appComponents "- $capabilityNames" '{templateParameters: {appComponents: $appComponents}}')
+
+      echo "Parameters: \"$parametersJson\""
+      echo "Branch for PR: \"$branch\""
+
+      # Define the request body
+      bodyJson=$(jq -n --argjson parameters "$parametersJson" --arg branch "$branch" '{
+        resources: {
+          repositories:               
+            {
+              self: {
+                refName: $branch
+              }
+            }
+        },
+        templateParameters: $parameters.templateParameters
+      }')
+
+      echo "Request body: \"$bodyJson\""
+
+      # Define the URL
+      url="https://dev.azure.com/${organization}/${project}/_apis/pipelines/${pipelineId}/runs?api-version=7.1"
+
+      # Trigger the pipeline
+      response=$(curl -s -w "%{http_code}" "${headers[@]}" -X POST -d "$bodyJson" "$url")
+      http_code=${response: -3}
+      content=${response::-3}
+
+      if [ $http_code -eq 200 ]; then
+          run_id=$(echo "$content" | jq -r '.id')
+          echo "Pipeline triggered successfully. Run ID: $run_id"
+      else
+          echo "Failed to trigger pipeline. HTTP Status Code: $http_code"
+          echo "Response: $content"
+          exit 1
+      fi
     displayName: 'Trigger Azure DevOps Pipeline'
     env:        
       AZURE_DEVOPS_ORG: nanoFramework
