adjusting pipeline to test

diff --git a/azure-boostrap.yaml b/azure-boostrap.yaml
--- a/azure-boostrap.yaml
+++ b/azure-boostrap.yaml
@@ -30,6 +30,13 @@ jobs:
   pool:
     vmImage: 'ubuntu-latest'
 
+  variables:
+    AZURE_DEVOPS_ORG: nanoFramework
+    AZURE_DEVOPS_PROJECT: nanoFramework.IoT.TestStream
+    AZURE_DEVOPS_PIPELINE_ID: 111
+    AZURE_POOL_NAME: TestStream
+    AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
+
   steps:   
   - script: |
       # Validate required environment variables
@@ -112,6 +119,7 @@ jobs:
       if [ $http_code -eq 200 ]; then
           run_id=$(echo "$content" | jq -r '.id')
           echo "Pipeline triggered successfully. Run ID: $run_id"
+          echo "##vso[task.setvariable variable=run_id]$run_id"
       else
           echo "Failed to trigger pipeline. HTTP Status Code: $http_code"
           echo "Response: $content"
@@ -119,9 +127,42 @@ jobs:
       fi
     displayName: 'Trigger Azure DevOps Pipeline'
     env:        
-      AZURE_DEVOPS_ORG: nanoFramework
-      AZURE_DEVOPS_PROJECT: nanoFramework.IoT.TestStream
-      AZURE_DEVOPS_PIPELINE_ID: 111
-      AZURE_POOL_NAME: TestStream
-      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
       BUILD_SOURCEBRANCH: $(Build.SourceBranch)
+  
+  - script: |
+      echo "Pipeline to monitor Run ID: $(run_id)"
+      # Define the URL to get the pipeline run status
+      url="https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/pipelines/${AZURE_DEVOPS_PIPELINE_ID}/runs/$(run_id)?api-version=7.1"
+
+      # Loop to monitor the pipeline run status
+      while true; do
+          response=$(curl -s -w "%{http_code}" -H "Authorization: Basic $(echo -n ":${AZURE_DEVOPS_PAT}" | base64)" -X GET "$url")
+          http_code=${response: -3}
+          content=${response::-3}
+
+          if [ $http_code -eq 200 ]; then
+              state=$(echo "$content" | jq -r '.state')
+              result=$(echo "$content" | jq -r '.result')
+
+              echo "Pipeline run state: $state"
+
+              if [ "$state" == "completed" ]; then
+                  echo "Pipeline run completed with result: $result"
+                  if [ "$result" == "succeeded" ]; then
+                      exit 0
+                  else
+                      exit 1
+                  fi
+              fi
+          else
+              echo "Failed to get pipeline run status. HTTP Status Code: $http_code"
+              echo "Response: $content"
+              exit 1
+          fi
+
+          # Wait for a while before checking again
+          sleep 30
+      done
+    displayName: 'Monitoring Azure DevOps pipeline'
+    env:
+      run_id: $(run_id)
