Change analysis of PR title to description

diff --git a/bootstrap.yml b/bootstrap.yml
--- a/bootstrap.yml
+++ b/bootstrap.yml
@@ -50,27 +50,28 @@ steps:
       content=${response::-3}
 
       if [ $http_code -eq 200 ]; then  
-          prTitle=$(echo "$content" | jq -r '.title')  
-          if [ "$prTitle" = "null" ]; then  
-              echo "Error: Failed to extract PR title from response"  
-              exit 1  
-          fi  
+        prDescription=$(echo "$content" | jq -r '.body')  
+        if [ "$prDescription" = "null" ]; then  
+            echo "Error: Failed to extract PR description from response"  
+            exit 1  
+        fi
       else  
           echo "Error: Failed to fetch PR details. Status code: $http_code"  
           echo "Response: $content"  
           exit 1  
       fi  
 
-      echo "PR Title: $prTitle"
+      echo "PR description: $prDescription"
 
       # Get the PR creator
       prCreator=$(echo "$content" | jq -r '.user.login')
 
       echo "PR Creator: $prCreator"
 
-      # Check if the PR creator is nfbot and set skipHardwareTest accordingly
-      # This is to skip the hardware test for PRs created by nfbot, so for bump PRs
-      if [ "$prCreator" == "nfbot" ] || [[ "$prTitle" == "[version update]"* ]]; then
+      # Check if the PR creator is nfbot AND description includes the version update tag, 
+      # and set skipHardwareTest accordingly
+      # This is to skip the hardware test for update PRs created by nfbot
+      if [ "$prCreator" == "nfbot" ] && [[ "$prDescription" == "[version update]"* ]]; then
           skipHardwareTest=true
       else
           skipHardwareTest=false
