adding skip hardware tests when bump version

diff --git a/bootstrap.yml b/bootstrap.yml
--- a/bootstrap.yml
+++ b/bootstrap.yml
@@ -63,6 +63,21 @@ steps:
 
       echo "PR Title: $prTitle"
 
+      # Get the PR creator
+      prCreator=$(echo "$content" | jq -r '.user.login')
+
+      echo "PR Creator: $prCreator"
+
+      # Check if the PR creator is nfbot and set skipHardwareTest accordingly
+      # This is to skip the hardware test for PRs created by nfbot, so for bump PRs
+      if [ "$prCreator" == "nfbot" ] || [[ "$prTitle" == "[version update]"* ]]; then
+          skipHardwareTest=true
+      else
+          skipHardwareTest=false
+      fi
+
+      echo "Skip Hardware Test: $skipHardwareTest"
+
       # Encode the PAT
       patEncoded=$(echo -n ":${AZURE_DEVOPS_PAT}" | base64)
 
@@ -72,29 +87,33 @@ steps:
         -H "Content-Type: application/json"
       )
 
-      # Get the pool ID
-      url="https://dev.azure.com/${organization}/_apis/distributedtask/pools?poolName=${poolName}&api-version=7.1"
-      AZP_POOL_AGENTS=$(curl -s "${headers[@]}" -X GET "$url")
-      poolId=$(echo "$AZP_POOL_AGENTS" | jq -r '.value[0].id')
-
-      echo "Pool ID: $poolId"
-
-      # Define the URL to get all agents in the pool
-      url="https://dev.azure.com/${organization}/_apis/distributedtask/pools/${poolId}/agents?includeCapabilities=true&api-version=7.1"
-
-      response=$(curl -s -w "%{http_code}" "${headers[@]}" -X GET "$url")
-      http_code=${response: -3}
-      content=${response::-3}
-
-      if [ $http_code -eq 200 ]; then
-          # Extract all userCapabilities names for online and enabled agents as a unique list
-          capabilityNames=$(echo "$content" | jq -r '[.value[] | select(.status == "online" and .enabled == true) | .userCapabilities | keys] | unique | flatten | join("\n- ")')
+      if [ skipHardwareTest == true ]; then
+        capabilityNames = "none";
       else
-          echo "Failed to retrieve agent capabilities. HTTP Status Code: $http_code"
-          echo "Response: \"$content\""
-          exit 1
+        # Get the pool ID
+        url="https://dev.azure.com/${organization}/_apis/distributedtask/pools?poolName=${poolName}&api-version=7.1"
+        AZP_POOL_AGENTS=$(curl -s "${headers[@]}" -X GET "$url")
+        poolId=$(echo "$AZP_POOL_AGENTS" | jq -r '.value[0].id')
+
+        echo "Pool ID: $poolId"
+
+        # Define the URL to get all agents in the pool
+        url="https://dev.azure.com/${organization}/_apis/distributedtask/pools/${poolId}/agents?includeCapabilities=true&api-version=7.1"
+
+        response=$(curl -s -w "%{http_code}" "${headers[@]}" -X GET "$url")
+        http_code=${response: -3}
+        content=${response::-3}
+
+        if [ $http_code -eq 200 ]; then
+            # Extract all userCapabilities names for online and enabled agents as a unique list
+            capabilityNames=$(echo "$content" | jq -r '[.value[] | select(.status == "online" and .enabled == true) | .userCapabilities | keys] | unique | flatten | join("\n- ")')
+        else
+            echo "Failed to retrieve agent capabilities. HTTP Status Code: $http_code"
+            echo "Response: \"$content\""
+            exit 1
+        fi
+        echo "Unique userCapabilities names: \"$capabilityNames\""
       fi
-      echo "Unique userCapabilities names: \"$capabilityNames\""
 
       # Prepare the parameters
       parametersJson=$(jq -n --arg appComponents "- $capabilityNames" '{templateParameters: {appComponents: $appComponents}}')
