testing adding full Windows

diff --git a/test.yml b/test.yml
--- a/test.yml
+++ b/test.yml
@@ -39,7 +39,7 @@ stages:
               path: '$(System.DefaultWorkingDirectory)'
 
           - task: DotNetCoreCLI@2
-            displayName: 'Install nanoff'
+            displayName: 'Linux Install nanoff'
             condition: eq(variables['Agent.OS'], 'Linux')
             inputs:
               command: custom
@@ -47,7 +47,7 @@ stages:
               arguments: 'install nanoff --tool-path /azp/tools'
 
           - task: DotNetCoreCLI@2
-            displayName: 'Install nanoff'
+            displayName: 'Windows Install nanoff'
             condition: eq(variables['Agent.OS'], 'Windows_NT')
             inputs:
               command: custom
@@ -90,7 +90,7 @@ stages:
                     echo "Flashing failed after $MAX_RETRIES attempts."
                     exit 1
                 fi
-              displayName: 'Flash device'
+              displayName: 'Linux Flash device'
               condition: eq(variables['Agent.OS'], 'Linux')
               retryCountOnTaskFailure: 3
 
@@ -134,7 +134,7 @@ stages:
                     Write-Host "Flashing failed after $MAX_RETRIES attempts."
                     exit 1
                 }
-              displayName: 'Flash device'
+              displayName: 'Windows Flash device'
               condition: eq(variables['Agent.OS'], 'Windows_NT')
               retryCountOnTaskFailure: 3
 
@@ -147,8 +147,31 @@ stages:
                 sed -i "s|<RealHardwarePort>.*<\/RealHardwarePort>|<RealHardwarePort>$(echo $SerialPort)<\/RealHardwarePort>|g" $(System.DefaultWorkingDirectory)/Artifacts/${{ split(tests, ',')[0]}}
                 cat $(System.DefaultWorkingDirectory)/Artifacts/${{ split(tests, ',')[0]}}
                 exit $?
-              displayName: 'Update nano.runsettings'
+              displayName: 'Linux Update nano.runsettings'
               condition: eq(variables['Agent.OS'], 'Linux')
+
+            - powershell: |
+                # Replace <IsRealHardware>False</IsRealHardware> by <IsRealHardware>True</IsRealHardware> in nano.runsettings
+                $runsettingsPath = "$(System.DefaultWorkingDirectory)\Artifacts\${{ split(tests, ',')[0]}}"
+                (Get-Content -Path $runsettingsPath) -replace '<IsRealHardware>False</IsRealHardware>', '<IsRealHardware>True</IsRealHardware>' | Set-Content -Path $runsettingsPath
+                (Get-Content -Path $runsettingsPath) -replace '<ResultsDirectory>.*</ResultsDirectory>', '<ResultsDirectory>./TestResults</ResultsDirectory>' | Set-Content -Path $runsettingsPath
+
+                # Read the configuration.json file
+                $configPath = "$(Agent.HomeDirectory)\configuration.json"
+                $configJson = Get-Content -Raw -Path $configPath | ConvertFrom-Json
+
+                # Get the SerialPort value for the specified app component
+                $appComponent = '${{ parameters.appComponents }}'
+                $SerialPort = $configJson.capabilities.$appComponent
+
+                # Replace the serial port by the one in the configuration for parameters.appComponents
+                (Get-Content -Path $runsettingsPath) -replace '<RealHardwarePort>.*</RealHardwarePort>', "<RealHardwarePort>$SerialPort</RealHardwarePort>" | Set-Content -Path $runsettingsPath
+
+                # Output the modified file
+                Get-Content -Path $runsettingsPath
+                exit $LASTEXITCODE
+              displayName: 'Windows Update nano.runsettings'
+              condition: eq(variables['Agent.OS'], 'Windows_NT')
 
             - bash: |
                 # Maximum number of retries
@@ -188,11 +211,54 @@ stages:
                         break
                     fi
                 done
-              displayName: 'Run tests'
+              displayName: 'Linux Run tests'
               timeoutInMinutes: 120
               retryCountOnTaskFailure: 3
               condition: eq(variables['Agent.OS'], 'Linux')
             
+            - powershell: |
+                # Maximum number of retries
+                $MAX_RETRIES = ${{ parameters.MaxRetries }}
+                # Delay between retries in seconds
+                $DELAY = 2
+                # Initialize the counter
+                $attempt = 0
+                # Define the base directory to search in
+                $BASE_DIR = "$(System.DefaultWorkingDirectory)\Artifacts"
+
+                # Use the Get-ChildItem command to search for paths starting with packages/nanoFramework.TestFramework
+                $TESTADAPTER_PATH = (Get-ChildItem -Path $BASE_DIR -Recurse -Directory | Where-Object { $_.FullName -match "packages\\nanoFramework.TestFramework.*" } | Select-Object -First 1).FullName
+
+                # Extract the directory path from the unitTestRunsettings parameter
+                $UNIT_TEST_RUNSETTINGS_DIR = Split-Path -Path "$BASE_DIR\${{ split(tests, ',')[0] }}"
+
+                # Loop to retry the function call
+                while ($attempt -lt $MAX_RETRIES) {
+                    $RESULT_TEST = & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "$BASE_DIR\${{ split(tests, ',')[1] }}" /Settings:"$BASE_DIR\${{ split(tests, ',')[0]}}" /TestAdapterPath:"$TESTADAPTER_PATH" /Logger:trx
+                    Write-Output "$RESULT_TEST"
+                    if ($RESULT_TEST -match "Couldn't connect to the device" -or $RESULT_TEST -match "Couldn't find any valid nanoDevice") {
+                        Write-Output "Test failed. Retrying in $DELAY seconds..."
+                        # we need to delete the trx file to avoid confusion but we keep the last one
+                        if ($attempt -eq $MAX_RETRIES) {
+                            Write-Output "Test failed after $MAX_RETRIES attempts."
+                            exit 1
+                        } else {
+                            Get-ChildItem -Path "$UNIT_TEST_RUNSETTINGS_DIR\TestResults" -Filter *.trx | Remove-Item -Force
+                            $attempt++
+                            Start-Sleep -Seconds $DELAY
+                        }
+                    } elseif ($RESULT_TEST -match "The argument .* is invalid.") {
+                        Write-Output "Test failed as arguments are not valid."
+                        exit 1
+                    } else {
+                        break
+                    }
+                }
+              displayName: 'Windows Run tests'
+              timeoutInMinutes: 120
+              retryCountOnTaskFailure: 3
+              condition: eq(variables['Agent.OS'], 'Windows_NT')
+
             - task: PublishTestResults@2
               inputs:
                 testResultsFormat: 'VSTest'
@@ -210,4 +276,4 @@ stages:
                 # Optional: Print a message indicating completion
                 echo "All .trx files have been removed from $unitTestRunsettings"
               displayName: Cleaning tests results
-              condition: eq(variables['Agent.OS'], 'Linux')
+              # condition: eq(variables['Agent.OS'], 'Linux')
