adjsuting test retries

diff --git a/test.yml b/test.yml
--- a/test.yml
+++ b/test.yml
@@ -56,19 +56,19 @@ stages:
                 echo "$RESULT_TEST"
                 if [[ "$RESULT_TEST" == *"Couldn't connect to the device"* ]]; then
                     echo "Test failed. Retrying in $DELAY seconds..."
-                    # we need to delete the trx file to avoid confusion
-                    find $(System.DefaultWorkingDirectory)/Artifacts/UnitTestStream/TestResults -type f -name "*.trx" -exec rm -f {} \;
-                    ((attempt++))
-                    sleep $DELAY
+                    # we need to delete the trx file to avoid confusion but we keep the last one
+                    if [ $attempt -eq $MAX_RETRIES ]; then
+                      echo "Test failed after $MAX_RETRIES attempts."
+                      exit 1
+                    else
+                      find $(System.DefaultWorkingDirectory)/Artifacts/UnitTestStream/TestResults -type f -name "*.trx" -exec rm -f {} \;
+                      ((attempt++))
+                      sleep $DELAY
+                    fi
                 else
                     break
                 fi
-            done
-
-            if [ $attempt -eq $MAX_RETRIES ]; then
-                echo "Function failed after $MAX_RETRIES attempts."
-                exit 1
-            fi                        
+            done                     
           displayName: 'Run tests'
           timeoutInMinutes: 120
           retryCountOnTaskFailure: 10
